### ISSUE TITLE
As a registered user, see most/all boards when they login so that they can see their dashboard

### ISSUE THREAD

**Issue by IntelliJinceTech** [snowballDevs/kandoo#75]
### Description

[Provide a brief description of the issue or feature]

### Current Behavior (for bugs)

[Describe what is currently happening or the problem you're facing]

### Expected Behavior (for bugs)

[Describe what you expected to happen]

### Proposed Solution (for features)

[Describe your proposed solution or implementation for the feature]

### Additional Context (optional)

[Add any additional information or context about the issue or feature]

### Tasks (optional)

-   [ ] Fetch boards from DB and send them as a response
-   [ ] Grab all the boards saved in the DB and render them in the frontend
-   [ ] Implement Axios to handle requested Data
-   [ ] Begin thinking about putting requested data into state.

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]
