### ISSUE TITLE
Finished Frontend Tasks

### ISSUE THREAD

**Issue by IntelliJinceTech** [snowballDevs/kandoo#91]
### Description

[Provide a brief description of the issue or feature]

### Current Behavior (for bugs)

[Describe what is currently happening or the problem you're facing]

### Expected Behavior (for bugs)

[Describe what you expected to happen]

### Proposed Solution (for features)

[Describe your proposed solution or implementation for the feature]

### Additional Context (optional)

[Add any additional information or context about the issue or feature]

### Tasks (optional)

-   [x] Task card hover (shadow?)
-   [ ] Trash bin on task card
-   [x] No scroll on TaskCard / " ... " 
- [ ] Board / register button bg color/hover:bg color

- 

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]

**Comment by IntelliJinceTech** [comment]
I think as we discussed - we should not have the trash bin on a task card?

**Comment by IntelliJinceTech** [comment]
On a separate note, I have created separated tasks so that people can take on individual tasks (pun intended)
